import Head from "next/head";
import { useQuery } from "urql";
import Product from "../components/Product";
import { PRODUCT_QUERY } from "../lib/query";
import { Gallery } from "../styles/Gallery";
import Nav from "../components/Nav";

export default function Home() {
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;
  console.log("s1a", results);
  if (fetching) {
    return <p>Loading ...</p>;
  }
  if (error) {
    return <p>There is an error {error.message} ...</p>;
  }
  const products = data.products.data;
  console.log("s2", products);

  return (
    <div>
      <Head>
        <title>Styled Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Gallery>
          {products.map((product) => (
            <Product key={product.attributes.slug} product={product} />
          ))}
        </Gallery>
      </main>
    </div>
  );
}
